const GET_USER_DETAIL = "GET_USER_DETAIL";
const GET_USER_ROLE = "GET_USER_ROLE";
const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
const GET_STATUS_PRODUCT = "GET_STATUS_PRODUCT";

export { GET_USER_DETAIL, GET_USER_ROLE, SET_LOGIN_STATUS, GET_DETAIL_PRODUCT, GET_STATUS_PRODUCT };
