const GET_USER_DETAIL = "GET_USER_DETAIL";
const GET_USER_ROLE = "GET_USER_ROLE";
const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
const GET_PRODUCT_PREVIEW = "GET_PRODUCT_PREVIEW";

export { GET_USER_DETAIL, GET_USER_ROLE, SET_LOGIN_STATUS, GET_ALL_PRODUCT, GET_PRODUCT_PREVIEW };
